### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cupcakearmy** [juandagilc/Audio-Effects#1]
Hey hey, so I just started with vst development today, this repo is basically like a bible now for me xD
Would you add a license? so everybody can use it :)

Thanks for the amazing work!

**Comment by juandagilc** [comment]
Hi!
I'm glad you find it useful. At the bottom of the README file  you can find the license note, anybody can use it ;)
I will try to move it to a separate file soon, so it is more clear.
Thanks.

**Comment by cupcakearmy** [comment]
Oh nvm, I'm blind :) Thank for the quick reply
