### ISSUE TITLE
[Feature request] StudioRack integration

### ISSUE THREAD

**Issue by kmturley** [juandagilc/Audio-Effects#2]
I'm the lead developer of an open-source VST plugin manager called StudioRack:
https://github.com/studiorack

The aim of my project is to provide a free open-source way to manage VST plugin dependencies and their versions. I would love to add Audio-Effects to the StudioRack Registry, which would involve the following steps:

1. Publish a Github release containing the plugin source along with metadata plugins.json
2. Tag your Github repository with studiorack-plugin so it can be discovered
3. Wait for the studiorack-registry to index your plugin (every 24 hours)
4. Check the registry feed for your plugin to appear https://studiorack.github.io/studiorack-registry/

Wondering if you would be interested in collaborating to make this work? It would then allow users to install Audio-Effects using the StudioRack website, command-line tool or app?

Thanks!

**Comment by juandagilc** [comment]
I am not interested in doing that.

**Comment by kmturley** [comment]
No problem. Could you add a LICENSE file for the code?

**Comment by juandagilc** [comment]
https://github.com/juandagilc/Audio-Effects/issues/1#issuecomment-619484043

**Comment by kmturley** [comment]
I know that you have it in the README. README is not easily machine-parseable and does not appear in GitHub searches.

Adding a LICENSE file is the industry standard, only takes a minute using one of the premade templates:
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository
