### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by lattice0** [juandagilc/Audio-Effects#3]
I'm a bit confused. The readme says build but only tells how to clone.

I see no CMakeLists.txt.

How should I build?

Thank you so much

**Comment by juandagilc** [comment]
These plugins were made using the JUCE framework. In the folder of each plugin there is a .jucer file that you can open with the Projucer (JUCE's project manager). The instructions to clone the project are also to clone the version of JUCE that was used when the last commit of this repo was made, so you should be able to compile the Projucer and then build the plugins. In the Projucer you can choose what IDE or build system you want to use. I have not tried using CMake but I guess you can if you want.
